name: KosmicOpenSRC
main: me.McShovelYT.KosmicForms.Old.Main
version: 1.0
author: McShovelYT
description: A custom forms plugin
commands:
   kReload:
      description: Reloads the config
   kSetForm:
      description: Sets form level
   kGiveFormTP:
      description: Sets form tp
   kMenu:
      description: Opens form menu