name: KosmicOpenSRC
main: me.McShovelYT.KosmicForms.Old.Main
version: 2.5.2
author: McShovelYT
description: A custom forms plugin
commands:
   kReload:
      description: Reloads the config
      aliases: kr
   kSetForm:
      description: Sets form level
      aliases: ks
   kGiveFormTP:
      description: Sets form tp
      aliases: kg
   kMenu:
      description: Opens form menu
      aliases: km